project:
  type: website

website:
  title: "12th Iberian Prion Congress"
  reader-mode: true
  page-footer: "&copy; 2023-2024 Website developed by Michał Burdukiewicz, Carlos Pintado-Grima (IBB-UAB), Dino Gasparotto (UNITN) and Sara Canoyra Sanchez (CSIC). "
  navbar:
    background: primary
    search: true
    pinned: true
    hoverable: true
    left:
      - text: "Home"
        file: index.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/IberianPrion
      - icon: instagram
        href: https://www.instagram.com/iberianprionconference
      - icon: linkedin
        href: https://linkedin.com/company/iberianprionconference

format:
  html:
    page-layout: full
    theme: 
      light: [united, quarto_palette.scss]
    toc: true
    toc-location: right
    toc-title: " "